name: 'Action name'
description: 'Action description'
author: 'italia'

inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  repo:
    description: 'GitHub repository. e.g. italia/publiccode-parser-action'
    default: '${{ github.repository }}'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'activity'
  color: 'white'
