name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Star Count
        uses: ./
        id: sample
        with:
          repo: "italia/publiccode-parser-action"